version: '4.8.1'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tptd1234560
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: